import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Intro from "../components/intro";
import { supabase } from "../utils/supabaseClient";
import { useState, useEffect } from 'react'

export default function Home() {
  const [data, setData] = useState([])

  useEffect(() => {
    getData()
  }, [])

  async function getData() {
    try{
      let { data: datas, error, status } = await supabase
          .from('profiles')
          .select()
          
      if (error && status !== 406) {
          throw error
        }
      if (data) {
          setData(datas)
        }
      } catch (error){
          alert(error.message)
      }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Panhchana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Intro />

      <div>
            <h1>TODO List</h1>
            <ul>
                {data.map( d =>
                    <li key={d.id}>
                        {d.website} 
                    </li>
                )}
            </ul>
        </div>

    </div>
  );
}

